import json
import os
import re

def clean_date(date_str):
    if not date_str: return None
    # Hebrew to English Month Mapping
    hebrew_months = {
        'ינו': 'JAN', 'ינואר': 'JAN',
        'פבר': 'FEB', 'פברואר': 'FEB',
        'מרץ': 'MAR',
        'אפר': 'APR', 'אפריל': 'APR',
        'מאי': 'MAY',
        'יונ': 'JUN', 'יוני': 'JUN',
        'יול': 'JUL', 'יולי': 'JUL',
        'אוג': 'AUG', 'אוגוסט': 'AUG',
        'ספט': 'SEP', 'ספטמבר': 'SEP',
        'אוק': 'OCT', 'אוקטובר': 'OCT',
        'נוב': 'NOV', 'נובמבר': 'NOV',
        'דצמ': 'DEC', 'דצמבר': 'DEC'
    }
    
    cleaned = date_str.replace("'", "").replace("’", "")
    for heb, eng in hebrew_months.items():
        if heb in cleaned:
            cleaned = cleaned.replace(heb, eng)
            break # Replace first match
            
    # Remove prepositions like "ב" prefix logic is complex, just simple substitution for now
    cleaned = re.sub(r'ב([א-ת]+)', r'\1', cleaned) # Remove 'b' prefix
    
    # Simple alphanumeric + spaced check
    return cleaned.strip()

def create_gedcom(data_file="full_tree_data.json", output_file="mahalal_tree.ged"):
    if not os.path.exists(data_file):
        print(f"Error: {data_file} not found.")
        return

    with open(data_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    people = {str(p["id"]): p for p in data.get("personCards", [])}
    families = {str(f["ID"]): f for f in data.get("familyConnectors", [])}

    # Build relationship maps for GEDCOM linking
    parent_map = {}  # child_id -> family_id (FAMC)
    spouse_map = {}  # person_id -> list of family_ids (FAMS)

    for fam_id, fam in families.items():
        husb = str(fam.get("h", ""))
        wife = str(fam.get("w", ""))
        children = [str(c) for c in fam.get("c", [])]

        if husb and husb != "None":
            spouse_map.setdefault(husb, []).append(fam_id)
        if wife and wife != "None":
            spouse_map.setdefault(wife, []).append(fam_id)
        
        for child in children:
            parent_map[child] = fam_id

    lines = [
        "0 HEAD",
        "1 SOUR MyHeritageScraper",
        "1 GEDC",
        "2 VERS 5.5.1",
        "2 FORM LINEAGE-LINKED",
        "1 CHAR UTF-8",
        "1 SUBM @SUBM1@"
    ]

    # Create Individual Records
    count_indi = 0
    for pid, p in people.items():
        count_indi += 1
        lines.append(f"0 @I{pid}@ INDI")
        
        # Name
        fn = p.get("fn", "").strip()
        ln = p.get("ln", "").strip()
        if fn or ln:
            lines.append(f"1 NAME {fn} /{ln}/")
            if fn: lines.append(f"2 GIVN {fn}")
            if ln: lines.append(f"2 SURN {ln}")
        else:
            lines.append(f"1 NAME {p.get('n', 'Unknown')}")

        # Gender
        sex = p.get("g", "U")
        if sex == "M": lines.append("1 SEX M")
        elif sex == "F": lines.append("1 SEX F")
        else: lines.append("1 SEX U")

        # Events
        if p.get("b"):
            lines.append("1 BIRT")
            lines.append(f"2 DATE {clean_date(p.get('b'))}")
            if p.get("by"): # Birth Year
                 # If full date fails, year is fallback, but standard gedcom allows full date
                 pass

        if p.get("d"):
            lines.append("1 DEAT")
            lines.append(f"2 DATE {clean_date(p.get('d'))}")

        # Links
        if pid in parent_map:
            lines.append(f"1 FAMC @F{parent_map[pid]}@")
        
        if pid in spouse_map:
            for fam_id in spouse_map[pid]:
                lines.append(f"1 FAMS @F{fam_id}@")

    # Create Family Records
    count_fam = 0
    for fid, f in families.items():
        count_fam += 1
        lines.append(f"0 @F{fid}@ FAM")
        
        husb = str(f.get("h", ""))
        wife = str(f.get("w", ""))
        
        if husb and husb != "None": lines.append(f"1 HUSB @I{husb}@")
        if wife and wife != "None": lines.append(f"1 WIFE @I{wife}@")
        
        for c in f.get("c", []):
            lines.append(f"1 CHIL @I{c}@")

    lines.append("0 @SUBM1@ SUBM")
    lines.append("1 NAME Generated by Antigravity")
    lines.append("0 TRLR")

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    
    print(f"GEDCOM saved to {output_file}")
    print(f"Stats: {count_indi} Individuals, {count_fam} Families")

if __name__ == "__main__":
    create_gedcom()
