import json
import os
import sys
import re

def clean_date(date_str):
    if not date_str: return None
    hebrew_months = {
        'ינו': 'JAN', 'ינואר': 'JAN', 'פבר': 'FEB', 'פברואר': 'FEB', 'מרץ': 'MAR',
        'אפר': 'APR', 'אפריל': 'APR', 'מאי': 'MAY', 'יונ': 'JUN', 'יוני': 'JUN',
        'יול': 'JUL', 'יולי': 'JUL', 'אוג': 'AUG', 'אוגוסט': 'AUG', 'ספט': 'SEP', 'ספטמבר': 'SEP',
        'אוק': 'OCT', 'אוקטובר': 'OCT', 'נוב': 'NOV', 'נובמבר': 'NOV', 'דצמ': 'DEC', 'דצמבר': 'DEC'
    }
    cleaned = date_str.replace("'", "").replace("’", "")
    for heb, eng in hebrew_months.items():
        if heb in cleaned:
            cleaned = cleaned.replace(heb, eng)
            break
    cleaned = re.sub(r'ב([א-ת]+)', r'\1', cleaned)
    return cleaned.strip()

def create_gedcom(json_file):
    if not os.path.exists(json_file):
        print(f"File {json_file} not found.")
        return

    # Derive naming from JSON filename
    base_name = os.path.splitext(os.path.basename(json_file))[0]
    output_ged = f"{base_name}.ged"
    images_dir_name = f"{base_name}_photos" # Expected format from scraper
    
    # Check if images dir exists (relative to script or absolute)
    images_path_rel = images_dir_name

    with open(json_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Handle both new generic format and old format
    if "personCards" in data:
        people_list = data["personCards"]
        families_list = data.get("familyConnectors", [])
    else:
        # Maybe wrapped differently
        print("Unknown JSON format.")
        return

    people = {str(p["id"]): p for p in people_list}
    families = {str(f["ID"]): f for f in families_list}

    # Maps
    parent_map = {}
    spouse_map = {}

    for fam_id, fam in families.items():
        husb = str(fam.get("h", ""))
        wife = str(fam.get("w", ""))
        children = [str(c) for c in fam.get("c", [])]

        if husb and husb != "None": spouse_map.setdefault(husb, []).append(fam_id)
        if wife and wife != "None": spouse_map.setdefault(wife, []).append(fam_id)
        for child in children: parent_map[child] = fam_id

    lines = [
        "0 HEAD",
        "1 SOUR AntigravityScraper",
        "1 GEDC",
        "2 VERS 5.5.1",
        "2 FORM LINEAGE-LINKED",
        "1 CHAR UTF-8",
        "1 SUBM @SUBM1@"
    ]

    for pid, p in people.items():
        lines.append(f"0 @I{pid}@ INDI")
        
        # Names
        fn = p.get("fn", "").strip()
        ln = p.get("ln", "").strip()
        lines.append(f"1 NAME {fn} /{ln}/")
        if fn: lines.append(f"2 GIVN {fn}")
        if ln: lines.append(f"2 SURN {ln}")

        # Gender
        sex = p.get("g", "U")
        lines.append(f"1 SEX {sex}")

        # Basic Dates
        if p.get("b"):
            lines.append("1 BIRT")
            lines.append(f"2 DATE {clean_date(p.get('b'))}")
        if p.get("d"):
            lines.append("1 DEAT")
            lines.append(f"2 DATE {clean_date(p.get('d'))}")

        # Photos
        # Scraper saves them as {id}.jpg inside the folder
        # Check if we have a photo URL in data first
        if p.get("ph"):
            # Construct local path assumption
            ext = p['ph'].split('.')[-1].split('/')[0]
            if len(ext) > 4: ext = "jpg"
            photo_filename = f"{pid}.{ext}"
            
            lines.append("1 OBJE")
            lines.append(f"2 FILE {images_path_rel}/{photo_filename}")
            lines.append("2 FORM jpg")
            lines.append("2 TITL Profile Photo")

        # Links
        if pid in parent_map: lines.append(f"1 FAMC @F{parent_map[pid]}@")
        if pid in spouse_map:
            for fid in spouse_map[pid]: lines.append(f"1 FAMS @F{fid}@")

    for fid, f in families.items():
        lines.append(f"0 @F{fid}@ FAM")
        husb = str(f.get("h", ""))
        wife = str(f.get("w", ""))
        if husb and husb != "None": lines.append(f"1 HUSB @I{husb}@")
        if wife and wife != "None": lines.append(f"1 WIFE @I{wife}@")
        for c in f.get("c", []): lines.append(f"1 CHIL @I{c}@")

    lines.append("0 @SUBM1@ SUBM")
    lines.append("1 NAME Generated by Antigravity")
    lines.append("0 TRLR")

    with open(output_ged, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        
    print(f"GEDCOM generated: {output_ged}")
    print(f"Total: {len(people)} Individuals, {len(families)} Families")

if __name__ == "__main__":
    if len(sys.argv) > 1:
        create_gedcom(sys.argv[1])
    else:
        # Default fallback for testing
        create_gedcom("output/tree_OYYV76FKVHAB6KC7YBFWOXCTQTUXUTI_1_data.json")
